#define SECRET_SSID "somessid"
#define SECRET_PASS "somepass"
#define SECRET_WIFI_SSID = "somessid"
#define SECRET_API_SERVER = "someserver"
#define SECRET_BASIC_AUTH = "Authorization: Basic somebase64encodedpass"